package com.kindial.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConversationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllPropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationAutoGeneratedPropertiesEquals(expected, actual);
        assertConversationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAllUpdatablePropertiesEquals(Conversation expected, Conversation actual) {
        assertConversationUpdatableFieldsEquals(expected, actual);
        assertConversationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationAutoGeneratedPropertiesEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableFieldsEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation relevant properties")
            .satisfies(a -> assertThat(a.getLastMessageID()).as("check lastMessageID").isEqualTo(expected.getLastMessageID()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getConversationName()).as("check conversationName").isEqualTo(expected.getConversationName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConversationUpdatableRelationshipsEquals(Conversation expected, Conversation actual) {
        assertThat(actual)
            .as("Verify Conversation relationships")
            .satisfies(a -> assertThat(a.getProfiles()).as("check profiles").isEqualTo(expected.getProfiles()));
    }
}
