package com.kindial.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TraitAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraitAllPropertiesEquals(Trait expected, Trait actual) {
        assertTraitAutoGeneratedPropertiesEquals(expected, actual);
        assertTraitAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraitAllUpdatablePropertiesEquals(Trait expected, Trait actual) {
        assertTraitUpdatableFieldsEquals(expected, actual);
        assertTraitUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraitAutoGeneratedPropertiesEquals(Trait expected, Trait actual) {
        assertThat(actual)
            .as("Verify Trait auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraitUpdatableFieldsEquals(Trait expected, Trait actual) {
        assertThat(actual)
            .as("Verify Trait relevant properties")
            .satisfies(a -> assertThat(a.getTraitName()).as("check traitName").isEqualTo(expected.getTraitName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraitUpdatableRelationshipsEquals(Trait expected, Trait actual) {
        assertThat(actual)
            .as("Verify Trait relationships")
            .satisfies(a -> assertThat(a.getProfiles()).as("check profiles").isEqualTo(expected.getProfiles()));
    }
}
