spring.application.name=app

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.show-sql = true
spring.datasource.driverClassName = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.config.import=optional:file:.env[.properties]

spring.mvc.dispatch-options-request=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://accounts.google.com


##
oauth.client-id=${GOOGLE_CLIENT_ID}
oauth.client-secret=${GOOGLE_CLIENT_SECRET}
oauth.redirect-url=${REDIRECT_URL}
oauth.token-secret=${TOKEN_SECRET}
oauth.token-expiration=36000
app.client.url=${CLIENT_URL:http://localhost:3000}

google.drive.credentials.json=${GOOGLE_DRIVE_CREDENTIALS_JSON}
google.drive.shared.drive.id=${GOOGLE_DRIVE_SHARED_DRIVE_ID:}

google.cloud.speech.credentials.json=${GOOGLE_CLOUD_SPEECH_CREDENTIALS_JSON:}
